// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StrengthPlanner.Infrastructure.Persistence;

#nullable disable

namespace StrengthPlanner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701130226_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.ExerciseMuscle", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MuscleGroupId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Contribution")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("ExerciseId", "MuscleGroupId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("ExerciseMuscles");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.ExercisePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RepRangeMax")
                        .HasColumnType("integer");

                    b.Property<int>("RepRangeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TargetRir")
                        .HasColumnType("integer");

                    b.Property<int>("TargetSets")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("ExercisePlans");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.Mesocycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationWeeks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Mesocycles");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.MuscleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MuscleGroups");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.OneRepMaxRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValueKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("OneRepMaxRecords");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<decimal>("BodyweightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Sex")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("TrainingDaysPerWeek")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.SetLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExercisePlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("Rir")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExercisePlanId");

                    b.ToTable("SetLogs");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.TrainingWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeload")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MesocycleId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MesocycleId", "WeekNumber")
                        .IsUnique();

                    b.ToTable("TrainingWeeks");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.VolumeLandmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Mev")
                        .HasColumnType("integer");

                    b.Property<int>("Mrv")
                        .HasColumnType("integer");

                    b.Property<Guid>("MuscleGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroupId")
                        .IsUnique();

                    b.ToTable("VolumeLandmarks");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DayLabel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TrainingWeekId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingWeekId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.ExerciseMuscle", b =>
                {
                    b.HasOne("StrengthPlanner.Domain.Entities.Exercise", "Exercise")
                        .WithMany("Muscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StrengthPlanner.Domain.Entities.MuscleGroup", "MuscleGroup")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.ExercisePlan", b =>
                {
                    b.HasOne("StrengthPlanner.Domain.Entities.Exercise", "Exercise")
                        .WithMany("ExercisePlans")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StrengthPlanner.Domain.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("ExercisePlans")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.Mesocycle", b =>
                {
                    b.HasOne("StrengthPlanner.Domain.Entities.User", "User")
                        .WithMany("Mesocycles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.OneRepMaxRecord", b =>
                {
                    b.HasOne("StrengthPlanner.Domain.Entities.Exercise", "Exercise")
                        .WithMany("OneRepMaxRecords")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StrengthPlanner.Domain.Entities.User", "User")
                        .WithMany("OneRepMaxRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.Profile", b =>
                {
                    b.HasOne("StrengthPlanner.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("StrengthPlanner.Domain.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.SetLog", b =>
                {
                    b.HasOne("StrengthPlanner.Domain.Entities.ExercisePlan", "ExercisePlan")
                        .WithMany("SetLogs")
                        .HasForeignKey("ExercisePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExercisePlan");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.TrainingWeek", b =>
                {
                    b.HasOne("StrengthPlanner.Domain.Entities.Mesocycle", "Mesocycle")
                        .WithMany("Weeks")
                        .HasForeignKey("MesocycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesocycle");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.VolumeLandmark", b =>
                {
                    b.HasOne("StrengthPlanner.Domain.Entities.MuscleGroup", "MuscleGroup")
                        .WithOne("VolumeLandmark")
                        .HasForeignKey("StrengthPlanner.Domain.Entities.VolumeLandmark", "MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.WorkoutSession", b =>
                {
                    b.HasOne("StrengthPlanner.Domain.Entities.TrainingWeek", "TrainingWeek")
                        .WithMany("Sessions")
                        .HasForeignKey("TrainingWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingWeek");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("ExercisePlans");

                    b.Navigation("Muscles");

                    b.Navigation("OneRepMaxRecords");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.ExercisePlan", b =>
                {
                    b.Navigation("SetLogs");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.Mesocycle", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.MuscleGroup", b =>
                {
                    b.Navigation("ExerciseMuscles");

                    b.Navigation("VolumeLandmark");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.TrainingWeek", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.User", b =>
                {
                    b.Navigation("Mesocycles");

                    b.Navigation("OneRepMaxRecords");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("StrengthPlanner.Domain.Entities.WorkoutSession", b =>
                {
                    b.Navigation("ExercisePlans");
                });
#pragma warning restore 612, 618
        }
    }
}
